spring.application.name=a3

spring.datasource.url=jdbc:mysql://localhost:3306/a3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=seplus
spring.datasource.password=seplus

//\u3053\u3053\u3067springboot\u3092\u8d77\u52d5\u3059\u308b\u3068\u30c6\u30fc\u30d6\u30eb\u304c\u81ea\u52d5\u751f\u6210
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never